//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAgeWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewAgeWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutUs_Hovor {
            get {
                object obj = ResourceManager.GetObject("AboutUs_Hovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutUs_NoHovor {
            get {
                object obj = ResourceManager.GetObject("AboutUs_NoHovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG__4_ {
            get {
                object obj = ResourceManager.GetObject("BG__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse {
            get {
                object obj = ResourceManager.GetObject("Browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CataLogo {
            get {
                object obj = ResourceManager.GetObject("CataLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon catalogo_0YD_icon {
            get {
                object obj = ResourceManager.GetObject("catalogo_0YD_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Config {
            get {
                object obj = ResourceManager.GetObject("Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Contribute_Hovor {
            get {
                object obj = ResourceManager.GetObject("Contribute_Hovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Contribute_NoHovor {
            get {
                object obj = ResourceManager.GetObject("Contribute_NoHovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeltaCompressionDotNet {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeltaCompressionDotNet_MsDelta {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet_MsDelta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeltaCompressionDotNet_MsDelta1 {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet_MsDelta1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeltaCompressionDotNet_PatchApi {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet_PatchApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeltaCompressionDotNet1 {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Donate_Hovor {
            get {
                object obj = ResourceManager.GetObject("Donate_Hovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Donate_NoHovor {
            get {
                object obj = ResourceManager.GetObject("Donate_NoHovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fb {
            get {
                object obj = ResourceManager.GetObject("fb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fb_hover {
            get {
                object obj = ResourceManager.GetObject("fb_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forum_Hovor {
            get {
                object obj = ResourceManager.GetObject("Forum_Hovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forum_NoHovor {
            get {
                object obj = ResourceManager.GetObject("Forum_NoHovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ICSharpCode_SharpZipLib {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;ICSharpCode.SharpZipLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:ICSharpCode.SharpZipLib.Core.WindowsPathUtils&quot;&gt;
        ///            &lt;summary&gt;
        ///            WindowsPathUtils provides simple utilities for handling windows paths.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:ICSharpCode.SharpZipLib.Core.WindowsPathUtils.#ctor&quot;&gt;
        ///            &lt;summary&gt;
        ///            Initializes a new instance of the &lt;see cref=&quot;T:ICSh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICSharpCode_SharpZipLib1 {
            get {
                return ResourceManager.GetString("ICSharpCode_SharpZipLib1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ICSharpCode_SharpZipLib2 {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;ICSharpCode.SharpZipLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:ICSharpCode.SharpZipLib.Core.WindowsPathUtils&quot;&gt;
        ///            &lt;summary&gt;
        ///            WindowsPathUtils provides simple utilities for handling windows paths.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:ICSharpCode.SharpZipLib.Core.WindowsPathUtils.#ctor&quot;&gt;
        ///            &lt;summary&gt;
        ///            Initializes a new instance of the &lt;see cref=&quot;T:ICSh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICSharpCode_SharpZipLib3 {
            get {
                return ResourceManager.GetString("ICSharpCode_SharpZipLib3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MahApps_Metro {
            get {
                object obj = ResourceManager.GetObject("MahApps_Metro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;MahApps.Metro&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:ControlzEx.KeyboardNavigationEx&quot;&gt;
        ///            &lt;summary&gt;
        ///            Helper class for a common focusing problem.
        ///            The focus itself isn&apos;t the problem. If we use the common focusing methods the control get the focus
        ///            but it doesn&apos;t get the focus visual style.
        ///            The KeyboardNavigation class handles the visual style only if the control get  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MahApps_Metro1 {
            get {
                return ResourceManager.GetString("MahApps_Metro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MahApps_Metro2 {
            get {
                object obj = ResourceManager.GetObject("MahApps_Metro2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;MahApps.Metro&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:ControlzEx.KeyboardNavigationEx&quot;&gt;
        ///            &lt;summary&gt;
        ///            Helper class for a common focusing problem.
        ///            The focus itself isn&apos;t the problem. If we use the common focusing methods the control get the focus
        ///            but it doesn&apos;t get the focus visual style.
        ///            The KeyboardNavigation class handles the visual style only if the control get  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MahApps_Metro3 {
            get {
                return ResourceManager.GetString("MahApps_Metro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CSharp {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.WindowsAPICodePack&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRestartRecoveryManager&quot;&gt;
        ///            &lt;summary&gt;
        ///            Provides access to the Application Restart and Recovery
        ///            features available in Windows Vista or higher. Application Restart and Recovery lets an
        ///            application do some recovery work to save data before the process ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_WindowsAPICodePack {
            get {
                return ResourceManager.GetString("Microsoft_WindowsAPICodePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack_Shell {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack_Shell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.WindowsAPICodePack.Shell&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Microsoft.WindowsAPICodePack.Shell.EventHandlerExtensionMethods&quot;&gt;
        ///            &lt;summary&gt;
        ///            Provides extension methods for raising events safely.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:Microsoft.WindowsAPICodePack.Shell.EventHandlerExtensionMethods.SafeRaise(System.EventHandler,System.Object)&quot;&gt;
        ///            &lt;summ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_WindowsAPICodePack_Shell1 {
            get {
                return ResourceManager.GetString("Microsoft_WindowsAPICodePack_Shell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack1 {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Mdb {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Mdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Mdb1 {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Mdb1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Pdb {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Pdb1 {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Pdb1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Rocks {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Rocks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Rocks1 {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Rocks1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil1 {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Bold {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Light {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Regular {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MySql_Data {
            get {
                object obj = ResourceManager.GetObject("MySql_Data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MySql_Data1 {
            get {
                object obj = ResourceManager.GetObject("MySql_Data1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewAge_Thumbnail {
            get {
                object obj = ResourceManager.GetObject("NewAge_Thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NuGet_Squirrel {
            get {
                object obj = ResourceManager.GetObject("NuGet_Squirrel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NuGet_Squirrel1 {
            get {
                object obj = ResourceManager.GetObject("NuGet_Squirrel1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play_Hovor {
            get {
                object obj = ResourceManager.GetObject("Play_Hovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play_NoHovor {
            get {
                object obj = ResourceManager.GetObject("Play_NoHovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_Hovor {
            get {
                object obj = ResourceManager.GetObject("Settings_Hovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_NoHovor {
            get {
                object obj = ResourceManager.GetObject("Settings_NoHovor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Splat {
            get {
                object obj = ResourceManager.GetObject("Splat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Splat1 {
            get {
                object obj = ResourceManager.GetObject("Splat1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Squirrel {
            get {
                object obj = ResourceManager.GetObject("Squirrel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Squirrel1 {
            get {
                object obj = ResourceManager.GetObject("Squirrel1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Windows_Interactivity {
            get {
                object obj = ResourceManager.GetObject("System_Windows_Interactivity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Windows_Interactivity1 {
            get {
                object obj = ResourceManager.GetObject("System_Windows_Interactivity1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yt {
            get {
                object obj = ResourceManager.GetObject("yt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yt_hover {
            get {
                object obj = ResourceManager.GetObject("yt_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
